spring.application.name=ai-code-reviewer-backend
server.port=8081
xai.api-key=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
xai.model=llama-3.1-8b-instant
xai.api-url=https://api.groq.com/openai/v1/chat/completions
